import "./globals.css";
import Navbar from "@/app/components/Navbar";

export const metadata = {
  title: "Anwar Alamara",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body>
        <div className="container">
          <div className="xl:px-6">
            <Navbar />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
